### ISSUE TITLE
Button does not render in Cordova

### ISSUE THREAD

**Issue by mercantyle** [thinhvo0108/react-paypal-express-checkout#7]
This plugin is awesome in a browser, however the component does not render when I'm running inside of a Cordova-based mobile app (via MeteorJS) - I'm not getting any sort of error or indication as to why it isnt showing up - any ideas or suggestions that I might try? I have been unable to find any other way to get express checkout to work in React this way.

**Comment by thinhvo0108** [comment]
Sorry I was busy lately, have you found a work-around way for this yet?
I worked with Cordova mobile app before, since Cordova/phonegap has its own way to load libraries, so the way Cordova works with React may be tricky (not like the way browser works)

Therefore, this react paypal button library of mine may not work with Cordova at the moment!

There is an article about Phonegap & React for your reference: http://devgirl.org/2015/09/22/sample-phonegap-app-with-reactjs/

**Comment by thinhvo0108** [comment]
I close this issue since this was inactive for a while, and Cordova is not supported by this library at the moment!

Thanks
